server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/elcafetentaciondb
    username: postgres
    password: '@Jiassia1979'
    driver-class-name:  org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


        